default environment: int
#default environment: test

browserConfig:
  browser: edge
  screenshots: false
  headless: false
  timeout: 5

environment:
  int:
    url: https://www.selenium.dev/
    title: Selenium

  test:
    url: https://logback.qos.ch/
    title: Logback Home
